### ISSUE TITLE
Running on windows results in an IndexError

### ISSUE THREAD

**Issue by ChanceCarmichael** [hnoraa/pixelToMidi#1]
How to reproduce:
1. Create a virtual environment with python3.10
2. `pip install -U pip && pip install -r requirements.txt`
3. Run the script with python `python main.py`

Error:
\pixelToMidi-main> python .\main.py
creating MIDI
Traceback (most recent call last):
  File "C:\Users\adamm\Downloads\pixelToMidi-main\pixelToMidi-main\main.py", line 25, in <module>
    ptm.createMIDI()
  File "C:\Users\adamm\Downloads\pixelToMidi-main\pixelToMidi-main\pixelToMidi.py", line 16, in createMIDI
    self.midi.writeMidi()
  File "C:\Users\adamm\Downloads\pixelToMidi-main\pixelToMidi-main\MIDI.py", line 26, in writeMidi
    self.midiFile.writeFile(f)
  File "C:\Users\adamm\AppData\Local\Programs\Python\Python310\lib\site-packages\midiutil\MidiFile.py", line 1637, in writeFile
    self.close()
  File "C:\Users\adamm\AppData\Local\Programs\Python\Python310\lib\site-packages\midiutil\MidiFile.py", line 1688, in close
    self.tracks[i].closeTrack()
  File "C:\Users\adamm\AppData\Local\Programs\Python\Python310\lib\site-packages\midiutil\MidiFile.py", line 826, in closeTrack
    self.processEventList()
  File "C:\Users\adamm\AppData\Local\Programs\Python\Python310\lib\site-packages\midiutil\MidiFile.py", line 789, in processEventList
    self.deInterleaveNotes()
  File "C:\Users\adamm\AppData\Local\Programs\Python\Python310\lib\site-packages\midiutil\MidiFile.py", line 889, in deInterleaveNotes
    stack[noteeventkey].pop()
IndexError: pop from empty list

**Comment by ChanceCarmichael** [comment]
forgot to mention, this was run in windows 11, which is my tertiary os behind arch and archbuntu

**Comment by hnoraa** [comment]
I have been able to run this on Windows 11 without issue
